from decouple import config


KAFKA_VIDEO_DOWNLOADER_JOB_TOPIC = config("KAFKA_VIDEO_DOWNLOADER_JOB_TOPIC", cast=str)
KAFKA_BOOTSTRAP_SERVERS = config("KAFKA_BOOTSTRAP_SERVERS", cast=str)
BUCKET_NAME = config("BUCKET_NAME", cast=str)
KAFKA_VIDEO_DOWNLOADER_STATUS_TOPIC = config(
    "KAFKA_VIDEO_DOWNLOADER_STATUS_TOPIC", cast=str
)
