from decouple import config


GEMINI_MODEL = config("GEMINI_MODEL", cast=str)
GEMINI_API_KEY = config("GEMINI_API_KEY", cast=str)
COLLECTION_NAME = config("COLLECTION_NAME", cast=str)
VIDEO_DOWNLOADER_JOB_COLLECTION_NAME = config(
    "VIDEO_DOWNLOADER_JOB_COLLECTION_NAME", cast=str
)
FIRESTORE_DB_NAME = config("FIRESTORE_DB_NAME", cast=str)
KAFKA_VIDEO_DOWNLOADER_JOB_TOPIC = config("KAFKA_VIDEO_DOWNLOADER_JOB_TOPIC", cast=str)
KAFKA_BOOTSTRAP_SERVERS = config("KAFKA_BOOTSTRAP_SERVERS", cast=str)
KAFKA_VIDEO_DOWNLOADER_STATUS_TOPIC = config(
    "KAFKA_VIDEO_DOWNLOADER_STATUS_TOPIC", cast=str
)
KAFKA_API_KEY = config("KAFKA_API_KEY", cast=str)
KAFKA_API_SECRET = config("KAFKA_API_SECRET", cast=str)
FIRESTORE_COLLECTION_STREAM_METADATA = config(
    "FIRESTORE_COLLECTION_STREAM_METADATA", cast=str
)
