gcloud run deploy video-downloader \
  --source . \
  --platform managed \
  --region us-central1 \
  --allow-unauthenticated \
  --service-account="$SERVICE_ACCOUNT_EMAIL" \
  --set-env-vars GEMINI_MODEL="${GEMINI_MODEL}" \
  --set-env-vars GEMINI_API_KEY="${GEMINI_API_KEY}" \
  --set-env-vars BUCKET_NAME="${BUCKET_NAME}" \
  --set-env-vars PROJECT_NAME="${PROJECT_NAME}" \
  --set-env-vars SERVICE_ACCOUNT_KEY_PATH="${SERVICE_ACCOUNT_KEY_PATH}" \
  --set-env-vars COLLECTION_NAME="${COLLECTION_NAME}" \
  --set-env-vars VIDEO_DOWNLOADER_JOB_COLLECTION_NAME="${VIDEO_DOWNLOADER_JOB_COLLECTION_NAME}" \
  --set-env-vars FIRESTORE_DB_NAME="${FIRESTORE_DB_NAME}" \
  --set-env-vars SERVICE_ACCOUNT_EMAIL="${SERVICE_ACCOUNT_EMAIL}" \
  --set-env-vars KAFKA_VIDEO_DOWNLOADER_JOB_TOPIC="${KAFKA_VIDEO_DOWNLOADER_JOB_TOPIC}" \
  --set-env-vars KAFKA_VIDEO_DOWNLOADER_STATUS_TOPIC="${KAFKA_VIDEO_DOWNLOADER_STATUS_TOPIC}" \
  --set-env-vars KAFKA_BOOTSTRAP_SERVERS="${KAFKA_BOOTSTRAP_SERVERS}" \
  --set-env-vars GCP_PROJECT_ID="${GCP_PROJECT_ID}" \
  --set-env-vars SERVICE_NAME="${SERVICE_NAME}" \
  --set-env-vars REGION="${REGION}" \
  --set-env-vars SECRET_NAME="${SECRET_NAME}" \
  --set-env-vars KAFKA_API_KEY="${KAFKA_API_KEY}" \
  --set-env-vars KAFKA_API_SECRET="${KAFKA_API_SECRET}"
